### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-ml#24]
Hey @postfalk, I'd love to get your eyeballs on this whenever you have a chance. As a Python noobie I would love any and all advice you have to clean up and improve what I have.

Feel free to look around and provide feedback on any and all of it, but here are a few files in particular you might start with:
- [api/mira/handler.py](https://github.com/tnc-ca-geo/animl-ml/blob/master/api/mira/handler.py) (Lambda API handler/entry-point)
- [models/mira-large/code/inference.py](https://github.com/tnc-ca-geo/animl-ml/blob/master/models/mira-large/code/inference.py) (scripts that live on the model endpoint EC2 instances and pre/post process requests before/after inference)
- [notebooks/test-inference-pipeline.ipynb](https://github.com/tnc-ca-geo/animl-ml/blob/master/notebooks/test-inference-pipeline.ipynb) (Notebook for submitting images for object detection via Megadetector then species classification via MIRA API. NOTE: You'll need to create a ```.env``` file with the Megadetector API key in order to use their API. I'll send that to you separately)

**Comment by postfalk** [comment]
The first impression is that the code is really clean and the things I did found so far are rather matters of taste and not really bad style.

The biggest thing is that it would be great if you could implement comprehensive unit tests which would be a good start to optimize the code even more. I saw the functional test hitting the API and that is a good thing too but different and it is good practice to keep functional tests (having all APIs and preconditions in place) and self-contained unit tests not depending on any particular environment of services separated. Happy to chat about that. Following these principles is also a good guide how to chop up the code (creating units).

**api/mira/handler.py:**

The only thing where it shows a little bit that you are new to Python is that there are some places with a somewhat deep nesting of conditions but they are not out of the extraordinary. But sometimes it might be unnecessary to test whether a value is Falsy or not => 60-169

```def parse_multipart_req(body, content_type):``` This is a good example where it would be great to have a unit test because I would actually see what format of response you expecting because you would make it explicit as mock data in your test. In which case it would be easier for me to suggest simplification. But maybe the format is such that this is entirely the right way.

Matter of taste: I usually don't leave empty lines within units. I know it is common practice in Python but it also raises the question why do have a break here, are doing something different now (which might need to be a different unit). I don't think there is a need for most of those you have, especially not before the return statement which is already obvious enough. 

Speaking of return statements. There is controversy about returning as soon as possible which might save you a lot of else and elif or making the return statement the last line in a unit. I think first one is more Pythonic and the last one more general since their are languages that don't have return statements and return whatever the last expression in the block is. In Python I usually use the return early approach. 

Some Python fundamentalist say, you should not have single letter variables for whatever reasons. I think it is to promote human readability. But since you did not come across it, I guess Google does not care and I tend to agree.

**Comment by postfalk** [comment]
One more thing, I am not sure about. Does the code runs on the server as service? In that case it might be problematic to initialize the AWS service the way you do it because the initialization might expire at some point. 

```
client = boto3.client("runtime.sagemaker")
```

You might want to re-initialize the service whenever you need it. E.g. in run_inference or when there are limits to that for some reason, once an hour or so but I would try the former first.

**Comment by nathanielrindlaub** [comment]
Great! Closing this out for now but feel free to re-open if you have any other feedback.
